### PR TITLE
Use oasis-std

### LINKED ISSUE #8: update tutorial and documentation to use oasis-rs library

### PR DESCRIPTION
**Pull request by nhynes**
Resolves #8 

Depends on
* updating [oasislabs/owasm-std](https://github.com/oasislabs/owasm-std)
* https://github.com/oasislabs/owasm-abi/pull/22
* https://github.com/oasislabs/owasm-ethereum/pull/12

### CODE REVIEW

**Review by noahj — APPROVED** [review]

**Review by ryscheng — CHANGES_REQUESTED** [review]
Why is owasm-std going backwards in version numbers?

**Comment by nhynes** [comment]
> owasm-std

where do you see `owasm-std`?

**Comment by ryscheng** [comment]
Oh my bad, its oasis-std now. but its not published yet, you're blocked on me for that?

**Comment by ryscheng** [comment]
Why dont we use owasm-std and bump the major version?

**Comment by nhynes** [comment]
> Why dont we use owasm-std and bump the major version?

because this is a new library that includes new thing like xargo and a platform allocator

**Review by david-yan — APPROVED** [review]

**Comment by nhynes** [comment]
I'll remake this PR using the new [oasis_std](https://github.com/oasislabs/oasis-std) monorepo.

**Pull request closed without merging**
